"103188000101":
  apidomain: https://api.islpay.hk/gateway/api/scanpay
  channelpublickey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmVRTa/9YRsOMD84qXKnfktR1718FePbRrAep+LzLElXoZFumkfazgAIW54lU01LhDddyUJD9XnfotNx1uUNLvF/MCz56pQzvSNRNqTCx6M8wPARygILwzcb5KdyXRIIFjVirwFWQoPD5JTujsszwvOyIwkTsYgBLqrxaRC75ifwIDAQAB
  gatewayprivatekey: |-
    MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJZF1WY+G91d5pew
    9mTH5sMpQfF6k5pvMILc7pRriEVectB/QZ1EFXXrD9Nru3gcBq1DTCIEazR2m8WF
    /Yubf6PtZikGSb9tM/kiPZNnp2Wgmn85rzlBkIMjG2UAmN+pTSLk5ztSjCwRPMQp
    4uLVjHmEVR3mmM1H4XtL8uzJUdDhAgMBAAECgYBO068PhQEE7B7r744wa5QnR9sp
    ms0Ws8DUxKP6AzZmfRbpO/flUTOYuYeBtf+PD9SIysaDCaJa0OUBhjnsI9OeEj7t
    3Zwjt8nYRVdXykbKe6/jAAvgRwKHsqyzkVyQiMW+knk3HfIgvBjiJHkMJA2b5fVk
    +I70nivqUwAJ+eIb4QJBAMY2CEcb2sSHa68NONy4/VS3kgbW7OtntghUNE8ITdkO
    q/1MLIMbAb6Bf+SMObBSy92snFegnpG+Gs0Ph2H65fUCQQDCFc+LeEo7OhFV8QEY
    wV1U2XMHohHI3HQBFZJRgJcEIUdRtO4zSsAlxYqOj0uQHbG8J4neh5xNb0i77td8
    i/+9AkAeORTwCs5D00ZXLdPyy/5M0aThiBoeFvVJtdU4C9Ma+sK838WVxCNy8foX
    Vk5hlW5igbRhJCupm2wowmppRUGVAkEAlRLvoS65xZgqbJp6vyr2pw+GnRxNELzT
    lWmeQ1/DnvZ4szeHpnoJ8Hk0nZ9O6NkGBYFREk2TLp8FfORNO2rE+QJAFhyVRkyt
    tSv1rC96v5GI0OPltMB6njy5UsafWpJXnxc7NNOsd8rxFidOZyJNAMgUcGbcXZe1
    d/dD0K5NaP6UBQ==
  merchantid: "103188000101"
